### ISSUE TITLE
Evaluate cryptonite library

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/haskell-fido2#4]
We should evaluate the cryptonite library, and consider if there are other options we might want to rely on instead.

Candidates:
- https://github.com/Yubico/libfido2 (C library)

**Comment by Infinisil** [comment]
@arianvp also thought about not depending on cryptonite in https://github.com/arianvp/haskell-fido2/issues/25

**Comment by ErinvanderVeen** [comment]
Using `libfido2` is more than acceptable. Creating the bridge from Haskell to the C library might be hard, but we get most of this back in not having to implement our own logic for the crypto part. We still have to decide on the right API, but we will use `libfido2`.
