### ISSUE TITLE
FidoU2F attestation always results in `AttestationTypeSelf` even when not selfsigned

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/haskell-fido2#45]
**Describe the bug**
FidoU2F attestation always results in `AttestationTypeSelf` even when not selfsigned

**To Reproduce**
Perform FidoU2F Attestation with a non-self signing authenticator

**Expected behavior**
`AttestationTypeBasic` or some other form of Attestation should be resulted in.

**Comment by Infinisil** [comment]
Note that `AttestationTypeUncertain` should be returned in general. `Self` is not supported by `fido-u2f`
